// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(qrac_ffiFFI)
import qrac_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_qrac_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_qrac_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureQracFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


/**
 * 図鑑表示に必要な遺物属性（DB選択・画像合成は次フェーズ）。
 */
public struct Artifact {
    public var artifactHash: String
    public var baseRarity: UInt32
    public var eraBonus: UInt32
    public var finalRarity: UInt32
    public var isMythic: Bool
    public var civ: String
    public var era: String
    public var category: String
    /**
     * 型キー（=image_set_id, 提案01 判断D）。収集の imageSetId バックフィル・参照照合用。
     */
    public var imageSetId: Int64
    public var color: ColorMod
    public var dirtLayerId: String
    public var damage: Damage
    public var preservationScore: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(artifactHash: String, baseRarity: UInt32, eraBonus: UInt32, finalRarity: UInt32, isMythic: Bool, civ: String, era: String, category: String, 
        /**
         * 型キー（=image_set_id, 提案01 判断D）。収集の imageSetId バックフィル・参照照合用。
         */imageSetId: Int64, color: ColorMod, dirtLayerId: String, damage: Damage, preservationScore: Double) {
        self.artifactHash = artifactHash
        self.baseRarity = baseRarity
        self.eraBonus = eraBonus
        self.finalRarity = finalRarity
        self.isMythic = isMythic
        self.civ = civ
        self.era = era
        self.category = category
        self.imageSetId = imageSetId
        self.color = color
        self.dirtLayerId = dirtLayerId
        self.damage = damage
        self.preservationScore = preservationScore
    }
}

#if compiler(>=6)
extension Artifact: Sendable {}
#endif


extension Artifact: Equatable, Hashable {
    public static func ==(lhs: Artifact, rhs: Artifact) -> Bool {
        if lhs.artifactHash != rhs.artifactHash {
            return false
        }
        if lhs.baseRarity != rhs.baseRarity {
            return false
        }
        if lhs.eraBonus != rhs.eraBonus {
            return false
        }
        if lhs.finalRarity != rhs.finalRarity {
            return false
        }
        if lhs.isMythic != rhs.isMythic {
            return false
        }
        if lhs.civ != rhs.civ {
            return false
        }
        if lhs.era != rhs.era {
            return false
        }
        if lhs.category != rhs.category {
            return false
        }
        if lhs.imageSetId != rhs.imageSetId {
            return false
        }
        if lhs.color != rhs.color {
            return false
        }
        if lhs.dirtLayerId != rhs.dirtLayerId {
            return false
        }
        if lhs.damage != rhs.damage {
            return false
        }
        if lhs.preservationScore != rhs.preservationScore {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(artifactHash)
        hasher.combine(baseRarity)
        hasher.combine(eraBonus)
        hasher.combine(finalRarity)
        hasher.combine(isMythic)
        hasher.combine(civ)
        hasher.combine(era)
        hasher.combine(category)
        hasher.combine(imageSetId)
        hasher.combine(color)
        hasher.combine(dirtLayerId)
        hasher.combine(damage)
        hasher.combine(preservationScore)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeArtifact: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Artifact {
        return
            try Artifact(
                artifactHash: FfiConverterString.read(from: &buf), 
                baseRarity: FfiConverterUInt32.read(from: &buf), 
                eraBonus: FfiConverterUInt32.read(from: &buf), 
                finalRarity: FfiConverterUInt32.read(from: &buf), 
                isMythic: FfiConverterBool.read(from: &buf), 
                civ: FfiConverterString.read(from: &buf), 
                era: FfiConverterString.read(from: &buf), 
                category: FfiConverterString.read(from: &buf), 
                imageSetId: FfiConverterInt64.read(from: &buf), 
                color: FfiConverterTypeColorMod.read(from: &buf), 
                dirtLayerId: FfiConverterString.read(from: &buf), 
                damage: FfiConverterTypeDamage.read(from: &buf), 
                preservationScore: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: Artifact, into buf: inout [UInt8]) {
        FfiConverterString.write(value.artifactHash, into: &buf)
        FfiConverterUInt32.write(value.baseRarity, into: &buf)
        FfiConverterUInt32.write(value.eraBonus, into: &buf)
        FfiConverterUInt32.write(value.finalRarity, into: &buf)
        FfiConverterBool.write(value.isMythic, into: &buf)
        FfiConverterString.write(value.civ, into: &buf)
        FfiConverterString.write(value.era, into: &buf)
        FfiConverterString.write(value.category, into: &buf)
        FfiConverterInt64.write(value.imageSetId, into: &buf)
        FfiConverterTypeColorMod.write(value.color, into: &buf)
        FfiConverterString.write(value.dirtLayerId, into: &buf)
        FfiConverterTypeDamage.write(value.damage, into: &buf)
        FfiConverterDouble.write(value.preservationScore, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeArtifact_lift(_ buf: RustBuffer) throws -> Artifact {
    return try FfiConverterTypeArtifact.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeArtifact_lower(_ value: Artifact) -> RustBuffer {
    return FfiConverterTypeArtifact.lower(value)
}


/**
 * 色違い HSV 補正。
 */
public struct ColorMod {
    public var hShift: Double
    public var sMul: Double
    public var vMul: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(hShift: Double, sMul: Double, vMul: Double) {
        self.hShift = hShift
        self.sMul = sMul
        self.vMul = vMul
    }
}

#if compiler(>=6)
extension ColorMod: Sendable {}
#endif


extension ColorMod: Equatable, Hashable {
    public static func ==(lhs: ColorMod, rhs: ColorMod) -> Bool {
        if lhs.hShift != rhs.hShift {
            return false
        }
        if lhs.sMul != rhs.sMul {
            return false
        }
        if lhs.vMul != rhs.vMul {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(hShift)
        hasher.combine(sMul)
        hasher.combine(vMul)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeColorMod: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ColorMod {
        return
            try ColorMod(
                hShift: FfiConverterDouble.read(from: &buf), 
                sMul: FfiConverterDouble.read(from: &buf), 
                vMul: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: ColorMod, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.hShift, into: &buf)
        FfiConverterDouble.write(value.sMul, into: &buf)
        FfiConverterDouble.write(value.vMul, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeColorMod_lift(_ buf: RustBuffer) throws -> ColorMod {
    return try FfiConverterTypeColorMod.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeColorMod_lower(_ value: ColorMod) -> RustBuffer {
    return FfiConverterTypeColorMod.lower(value)
}


/**
 * 破損状態。
 */
public struct Damage {
    public var chip: Bool
    public var crack: Bool
    public var wear: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(chip: Bool, crack: Bool, wear: Bool) {
        self.chip = chip
        self.crack = crack
        self.wear = wear
    }
}

#if compiler(>=6)
extension Damage: Sendable {}
#endif


extension Damage: Equatable, Hashable {
    public static func ==(lhs: Damage, rhs: Damage) -> Bool {
        if lhs.chip != rhs.chip {
            return false
        }
        if lhs.crack != rhs.crack {
            return false
        }
        if lhs.wear != rhs.wear {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(chip)
        hasher.combine(crack)
        hasher.combine(wear)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDamage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Damage {
        return
            try Damage(
                chip: FfiConverterBool.read(from: &buf), 
                crack: FfiConverterBool.read(from: &buf), 
                wear: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: Damage, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.chip, into: &buf)
        FfiConverterBool.write(value.crack, into: &buf)
        FfiConverterBool.write(value.wear, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDamage_lift(_ buf: RustBuffer) throws -> Damage {
    return try FfiConverterTypeDamage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDamage_lower(_ value: Damage) -> RustBuffer {
    return FfiConverterTypeDamage.lower(value)
}


/**
 * 関連遺物（出土の系譜, 提案01 §5）。詳細画面「関連遺物」セクション用。
 */
public struct Reference {
    /**
     * 参照先の型キー（image_set_id）。
     */
    public var toSet: Int64
    /**
     * 'pair' | 'cites' | 'rival'。
     */
    public var kind: String
    /**
     * 参照先の型呼称（§3.4・詳細チップと同語彙）。
     */
    public var toLabel: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * 参照先の型キー（image_set_id）。
         */toSet: Int64, 
        /**
         * 'pair' | 'cites' | 'rival'。
         */kind: String, 
        /**
         * 参照先の型呼称（§3.4・詳細チップと同語彙）。
         */toLabel: String) {
        self.toSet = toSet
        self.kind = kind
        self.toLabel = toLabel
    }
}

#if compiler(>=6)
extension Reference: Sendable {}
#endif


extension Reference: Equatable, Hashable {
    public static func ==(lhs: Reference, rhs: Reference) -> Bool {
        if lhs.toSet != rhs.toSet {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.toLabel != rhs.toLabel {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(toSet)
        hasher.combine(kind)
        hasher.combine(toLabel)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeReference: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Reference {
        return
            try Reference(
                toSet: FfiConverterInt64.read(from: &buf), 
                kind: FfiConverterString.read(from: &buf), 
                toLabel: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Reference, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.toSet, into: &buf)
        FfiConverterString.write(value.kind, into: &buf)
        FfiConverterString.write(value.toLabel, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReference_lift(_ buf: RustBuffer) throws -> Reference {
    return try FfiConverterTypeReference.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReference_lower(_ value: Reference) -> RustBuffer {
    return FfiConverterTypeReference.lower(value)
}


/**
 * 合成済み画像（PNGバイト列＋寸法）＋解説文。
 */
public struct RenderedImage {
    public var width: UInt32
    public var height: UInt32
    public var png: Data
    /**
     * 選ばれたベース遺物の名称（DB由来）。
     */
    public var baseName: String
    /**
     * 型キー（=image_set_id, 提案01 判断D）。
     */
    public var imageSetId: Int64
    /**
     * 当たったフォールバック段（1..6, 7=GLOBAL）。
     */
    public var matchedStage: UInt8
    /**
     * 民明書房調の解説文（「詳説 世界の遺物」より抜粋の体裁。参照文を含みうる）。
     */
    public var description: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(width: UInt32, height: UInt32, png: Data, 
        /**
         * 選ばれたベース遺物の名称（DB由来）。
         */baseName: String, 
        /**
         * 型キー（=image_set_id, 提案01 判断D）。
         */imageSetId: Int64, 
        /**
         * 当たったフォールバック段（1..6, 7=GLOBAL）。
         */matchedStage: UInt8, 
        /**
         * 民明書房調の解説文（「詳説 世界の遺物」より抜粋の体裁。参照文を含みうる）。
         */description: String) {
        self.width = width
        self.height = height
        self.png = png
        self.baseName = baseName
        self.imageSetId = imageSetId
        self.matchedStage = matchedStage
        self.description = description
    }
}

#if compiler(>=6)
extension RenderedImage: Sendable {}
#endif


extension RenderedImage: Equatable, Hashable {
    public static func ==(lhs: RenderedImage, rhs: RenderedImage) -> Bool {
        if lhs.width != rhs.width {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        if lhs.png != rhs.png {
            return false
        }
        if lhs.baseName != rhs.baseName {
            return false
        }
        if lhs.imageSetId != rhs.imageSetId {
            return false
        }
        if lhs.matchedStage != rhs.matchedStage {
            return false
        }
        if lhs.description != rhs.description {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(width)
        hasher.combine(height)
        hasher.combine(png)
        hasher.combine(baseName)
        hasher.combine(imageSetId)
        hasher.combine(matchedStage)
        hasher.combine(description)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRenderedImage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RenderedImage {
        return
            try RenderedImage(
                width: FfiConverterUInt32.read(from: &buf), 
                height: FfiConverterUInt32.read(from: &buf), 
                png: FfiConverterData.read(from: &buf), 
                baseName: FfiConverterString.read(from: &buf), 
                imageSetId: FfiConverterInt64.read(from: &buf), 
                matchedStage: FfiConverterUInt8.read(from: &buf), 
                description: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: RenderedImage, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.width, into: &buf)
        FfiConverterUInt32.write(value.height, into: &buf)
        FfiConverterData.write(value.png, into: &buf)
        FfiConverterString.write(value.baseName, into: &buf)
        FfiConverterInt64.write(value.imageSetId, into: &buf)
        FfiConverterUInt8.write(value.matchedStage, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRenderedImage_lift(_ buf: RustBuffer) throws -> RenderedImage {
    return try FfiConverterTypeRenderedImage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRenderedImage_lower(_ value: RenderedImage) -> RustBuffer {
    return FfiConverterTypeRenderedImage.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * 解説文の言語。表示テキストのみに影響し、決定論（hash/属性）には無関係。
 */

public enum Lang {
    
    case ja
    case en
}


#if compiler(>=6)
extension Lang: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLang: FfiConverterRustBuffer {
    typealias SwiftType = Lang

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Lang {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .ja
        
        case 2: return .en
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Lang, into buf: inout [UInt8]) {
        switch value {
        
        
        case .ja:
            writeInt(&buf, Int32(1))
        
        
        case .en:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLang_lift(_ buf: RustBuffer) throws -> Lang {
    return try FfiConverterTypeLang.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLang_lower(_ value: Lang) -> RustBuffer {
    return FfiConverterTypeLang.lower(value)
}


extension Lang: Equatable, Hashable {}






#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt32: FfiConverterRustBuffer {
    typealias SwiftType = Int32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeReference: FfiConverterRustBuffer {
    typealias SwiftType = [Reference]

    public static func write(_ value: [Reference], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeReference.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Reference] {
        let len: Int32 = try readInt(&buf)
        var seq = [Reference]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeReference.read(from: &buf))
        }
        return seq
    }
}
public func categoryLabel(category: String, lang: Lang) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_qrac_ffi_fn_func_category_label(
        FfiConverterString.lower(category),
        FfiConverterTypeLang_lower(lang),$0
    )
})
}
/**
 * 軸単体の表示呼称（Q7=(i): Swift の civName/eraName/categoryName が呼ぶ単一の出所）。
 */
public func civLabel(civ: String, lang: Lang) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_qrac_ffi_fn_func_civ_label(
        FfiConverterString.lower(civ),
        FfiConverterTypeLang_lower(lang),$0
    )
})
}
/**
 * アセットディレクトリを設定（例: アプリ同梱の assets/ パス）。
 */
public func configureAssets(dir: String)  {try! rustCall() {
    uniffi_qrac_ffi_fn_func_configure_assets(
        FfiConverterString.lower(dir),$0
    )
}
}
/**
 * QR文字列 → 遺物（年は内容から自動抽出）。
 */
public func deriveQr(text: String) -> Artifact  {
    return try!  FfiConverterTypeArtifact_lift(try! rustCall() {
    uniffi_qrac_ffi_fn_func_derive_qr(
        FfiConverterString.lower(text),$0
    )
})
}
/**
 * QR文字列 → 遺物（年を明示。None=年代取得不可として +0）。
 */
public func deriveQrWithYear(text: String, year: Int32?) -> Artifact  {
    return try!  FfiConverterTypeArtifact_lift(try! rustCall() {
    uniffi_qrac_ffi_fn_func_derive_qr_with_year(
        FfiConverterString.lower(text),
        FfiConverterOptionInt32.lower(year),$0
    )
})
}
/**
 * 合本解説（型ペア・canonical, 判断E）。両型所持時に詳細画面で表示。
 * kind 不正値は 'pair' とみなす。
 */
public func describePair(setA: Int64, setB: Int64, kind: String, lang: Lang) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_qrac_ffi_fn_func_describe_pair(
        FfiConverterInt64.lower(setA),
        FfiConverterInt64.lower(setB),
        FfiConverterString.lower(kind),
        FfiConverterTypeLang_lower(lang),$0
    )
})
}
/**
 * 解説文のみを生成（画像なし・軽量）。言語切替時の再生成や展示室表示に使う。
 */
public func describeQr(text: String, lang: Lang) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_qrac_ffi_fn_func_describe_qr(
        FfiConverterString.lower(text),
        FfiConverterTypeLang_lower(lang),$0
    )
})
}
public func eraLabel(era: String, lang: Lang) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_qrac_ffi_fn_func_era_label(
        FfiConverterString.lower(era),
        FfiConverterTypeLang_lower(lang),$0
    )
})
}
/**
 * 型 `image_set_id` の関連遺物一覧（詳細画面「関連遺物」用, §5）。
 */
public func referencesOf(imageSetId: Int64, lang: Lang) -> [Reference]  {
    return try!  FfiConverterSequenceTypeReference.lift(try! rustCall() {
    uniffi_qrac_ffi_fn_func_references_of(
        FfiConverterInt64.lower(imageSetId),
        FfiConverterTypeLang_lower(lang),$0
    )
})
}
/**
 * QR文字列 → 合成画像（derive → DB選択 → 6層合成 → PNG）。lang は解説文の言語。
 */
public func renderQr(text: String, lang: Lang) -> RenderedImage  {
    return try!  FfiConverterTypeRenderedImage_lift(try! rustCall() {
    uniffi_qrac_ffi_fn_func_render_qr(
        FfiConverterString.lower(text),
        FfiConverterTypeLang_lower(lang),$0
    )
})
}
/**
 * 年指定つきレンダ（デバッグ/バランス確認用。None=年代取得不可として +0）。
 */
public func renderQrWithYear(text: String, year: Int32?, lang: Lang) -> RenderedImage  {
    return try!  FfiConverterTypeRenderedImage_lift(try! rustCall() {
    uniffi_qrac_ffi_fn_func_render_qr_with_year(
        FfiConverterString.lower(text),
        FfiConverterOptionInt32.lower(year),
        FfiConverterTypeLang_lower(lang),$0
    )
})
}
/**
 * 型呼称（判断C・Q7=(i)）。Swift はこれを呼んで参照先名／チップを Rust 語彙で表示する。
 */
public func typeLabel(civ: String, era: String, category: String, lang: Lang) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_qrac_ffi_fn_func_type_label(
        FfiConverterString.lower(civ),
        FfiConverterString.lower(era),
        FfiConverterString.lower(category),
        FfiConverterTypeLang_lower(lang),$0
    )
})
}
/**
 * image_set_id から型呼称を解決（GLOBAL/範囲外は汎称）。
 */
public func typeLabelForSet(imageSetId: Int64, lang: Lang) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_qrac_ffi_fn_func_type_label_for_set(
        FfiConverterInt64.lower(imageSetId),
        FfiConverterTypeLang_lower(lang),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_qrac_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_qrac_ffi_checksum_func_category_label() != 56745) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qrac_ffi_checksum_func_civ_label() != 15795) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qrac_ffi_checksum_func_configure_assets() != 6867) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qrac_ffi_checksum_func_derive_qr() != 35684) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qrac_ffi_checksum_func_derive_qr_with_year() != 25988) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qrac_ffi_checksum_func_describe_pair() != 5915) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qrac_ffi_checksum_func_describe_qr() != 59936) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qrac_ffi_checksum_func_era_label() != 9125) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qrac_ffi_checksum_func_references_of() != 16396) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qrac_ffi_checksum_func_render_qr() != 8441) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qrac_ffi_checksum_func_render_qr_with_year() != 28788) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qrac_ffi_checksum_func_type_label() != 26599) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_qrac_ffi_checksum_func_type_label_for_set() != 48400) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureQracFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all